# Generated by Django 4.0.5 on 2022-10-10 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('phone_number', models.CharField(max_length=100, null=True)),
                ('sex', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('other', 'other')], max_length=100, null=True)),
                ('birth_date', models.DateField(null=True)),
                ('Occupation', models.CharField(max_length=100, null=True)),
                ('education', models.CharField(choices=[('Professor', 'Professor'), ('Masters', 'Masters'), ('Degree', 'Degree'), ('High School', 'High School'), ('Others', 'Others')], max_length=100, null=True)),
                ('Address', models.CharField(max_length=100, null=True)),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(null=True)),
                ('payment_cart', models.CharField(choices=[('Tithe', 'Tithe'), ('Contribution', 'Contribution'), ('Collection', 'Collection'), ('Dues', 'Dues'), ('Others', 'Others')], max_length=100, null=True)),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('Cheque', 'Cheque'), ('Card', 'Card'), ('Mobile Money', 'Mobile Money'), ('Others', 'Others')], max_length=100, null=True)),
                ('date_paid', models.DateField(null=True)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='member.member')),
            ],
        ),
    ]
