# Generated by Django 4.0.5 on 2022-10-11 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='date_join',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
