# Generated by Django 4.0.5 on 2022-10-11 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_member_date_join'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='date_join',
            field=models.DateField(null=True),
        ),
    ]
